# Part2

Visualizing a Decision Tree - [Link](https://www.youtube.com/watch?v=tNa99PG8hR8&list=PLOU2XLYxmsIIuiBfYad6rFYQU_jL2ryal&index=6)

Import real dataset, add code to visualize it, and practice reading it.

Objectives:  
1-Import already includes Iris [dataset](http://scikit-learn.org/stable/datasets/) "load_iris"  
2-Train a classifier  
3-Predict label for new flower  
4-Visualize the tree

In [18]:
from sklearn.datasets import load_iris

iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])  #first row of dataflower
print(iris.target[50])  #contains the labels converted in integers

# print entire dataset
#for i in range(len(iris.target)):
#    print("%d- features %s label: %s" % (i, iris.data[i], iris.target[i]))



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
1


In [19]:
import numpy as np
from sklearn import tree

# found at indices: 0 , 50, 100 
test_idx = [0, 50, 100]

# training data, remove the data used in test
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# create new classifier
clf = tree.DecisionTreeClassifier()

# train on training data
clf.fit(train_data, train_target)

# what we expect 0 (setosa), 1 (Versicolor), 2 (Virginica)
print(test_target)
# get predicts
print(clf.predict(test_data))

[0 1 2]
[0 1 2]


### Vizualize with http://graphviz.org

In [27]:
# Visualize the tree, not working for me with python 3.5.2

#from sklearn.externals.six import StringIO
#import pydot

#dot_data = StringIO()
#tree.export_graphviz(clf, out_file=dot_data)
#graph = pydot.graph_from_dot_data(dot_data.getvalue())
#graph.write_pdf("iris.pdf")



#from sklearn.externals.six import StringIO
#import graphviz


#tree.export_graphviz(tree, out_file="mytree.dot")
#with open("mytree.dot") as f:
#    dot_graph = f.read()
#graphviz.Source(dot_graph)

import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.18.1.
